FROM node:13 as builder

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

USER node

COPY yarn.lock .
COPY package.json .

RUN yarn global add gatsby-cli
RUN yarn install

COPY . .

RUN ["yarn", "run", "build"]

FROM nginx:mainline-alpine

COPY --from=builder /home/node/app/public /usr/share/nginx/html