version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: ./client/eslintrc.json

checks:
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 150
  similar-code:
    enabled: false
  identical-code:
    enabled: false

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.less"
    - "**.scss"
    - "**.sss"

exclude_paths:
- ./client/static/**/*
- ./client/src/templates/b16-tomorrow-dark.css
